### ISSUE TITLE
Brew install error

### ISSUE THREAD

**Issue by qichengri** [rakutentech/jwkgen#7]
# Device
Apple M1

# Command
```bash
brew tap rakutentech/tap

brew install jwkgen
```

Error: jwkgen: wrong number of arguments (given 1, expected 0)

**Comment by FantaAI** [comment]
@qichengri  I face the same issue, you can try to clone the project, and execute 
`go get -u github.com/rakutentech/jwkgen`

**Comment by ziye-rao** [comment]
The above command didn't work for me in 2024.
Instead use:
`go install github.com/rakutentech/jwkgen@latest`

**Comment by boazy** [comment]
This issue was fixed in v1.4.8. The Homebrew Formula has been updated and now it also includes a proper build for Apple Silicon (arm64).
